# Logging
logging:
  file: app.log

# Spring Security default user name and password
spring.security.user:
  name: actuator
  password: actuator
  roles: ACTUATOR_ADMIN
  
spring:
#  profiles:
#    active: "dev"
    
  servlet:
    multipart:
      max-file-size: 100MB 
      max-request-size: 100MB
      enabled: true    

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

--- 
spring:
  profiles: dev
  banner:
    location: banner-dev.txt 
  datasource:
    url: jdbc:sqlserver://desesqlbdmg:2002;databaseName=bdseg
    username: sist_rpsr
    password: Ho1#h=j4
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
app:
  storage.location: /store
  
---   
spring:
  profiles: docker
  banner:
    location: banner-docker.txt 
    #datasource:
    #url: jdbc:sqlserver://desesqlbdmg:2002;databaseName=bdseg
    # username: sist_rpsr
    #password: Ho1#h=j4
    #driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #jpa:
    #  show-sql: false
app:
  storage.location: /store
